---
title: "Homework 10"
author: "Group 8"
date: "November 19, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Ignore this all for now, it's just a bunch of operations


data=read.csv('PlayersGroupedByMonth.csv')
par(mfrow=c(2,2))
plot(data$CollegeGames,data$Minutes)
plot(data$CollegeGames,data$Pts36,ylim=c(0,30))
plot(data$CollegeGames,data$Ast36)
plot(data$CollegeGames,data$TO36)

bin=rep(0,length(data$br_url))
#for (i in 1:length(bin)){
  if (data$College_Games[i] <= 35 && data$College_Games[i] >= 1) {
  bin[i]=1
  } else if (data$College_Games[i] >= 36 && data$College_Games[i] <= 70) {
  bin[i]=2
  } else if (data$College_Games[i] >= 71 && data$College_Games[i] <= 105) {
  bin[i]=3
  } else if (data$College_Games[i] >= 106 && data$College_Games[i] <= 152) {
  bin[i]=4
  } else if (data$Intl_Minutes[i] <= 669 && data$Intl_Minutes[i] >= 2) {
  bin[i]=5
  } else if (data$Intl_Minutes[i] >= 670 && data$Intl_Minutes[i] <= 1221) {
  bin[i]=6
  } else if (data$Intl_Minutes[i] >= 1222 && data$Intl_Minutes[i] <= 3328) {
  bin[i]=7
  } else if (data$Intl_Minutes[i] >= 3329 && data$Intl_Minutes[i] <= 13659) {
  bin[i]=8
}
}
data$bin=bin
data$minsgroup<-NULL
#write.csv(data,'PlayersGroupedByMonth2.csv')



par(mfrow=c(2,2))
plot(data$Month,data$Minutes,col=data$MinBin)
plot(data$Month,data$Pts36,col=data$MinBin)
plot(data$Month,data$Ast36,col=data$MinBin)
plot(data$Month,data$TO36,col=data$MinBin)



```


Here is the good stuff!
```{r}
library(ggplot2)
data=read.csv('PlayersGroupedByMonthAndBin.csv')
cols <- c("0"="black",'1'='greenyellow','2'='forestgreen','3'='dodgerblue','4'='darkorchid1','5'='yellow','6'='orange','7'='darksalmon','8'='firebrick3')
ggplot(data, aes(x = Month, y = Game_Score, group = Bin, color = Bin)) + 
  geom_point(aes(color = factor(Bin)))+ scale_colour_manual(values = cols) +
  geom_line(col = 'gray')+
  scale_x_continuous(breaks = c(10,11,12,1,2,3,4,5,6))
```

