---
title: "HW 09"
author: "Group 8"
date: "11/13/2019"
output: pdf_document
---

We are scraping from the College Basketball page of Sports Reference. 
One example url is https://sports-reference.com/cbb/players/carmelo-anthony-1.html
We are interested in how many games they played and the total minutes to measure the correlation between college experience and rookie year performance.
```{r, echo=TRUE}
library(XML)
library(RCurl)
library(stringr)
```

```{r, echo=TRUE}
# read all rookie stats in
data <- read.csv('AllRookieDataWithURL.csv')
```

```{r, echo=TRUE}
# get urls from br_url column
all_urls <- as.vector(unique(data$br_url))
# get the length of urls
nurls <- length(all_urls)
# create a dataframe for players with NCAA experience
intl_df <- data.frame(matrix(ncol = 3, nrow = nurls))
```

```{r, echo=TRUE}
# Scrape college careers
for (i in 1:nurls) {
  # get the appopriate url address
  u <- paste0("https://sports-reference.com/cbb/players/",
              all_urls[i],".html")
  if (url.exists(url = u)) {
    download.file(u, destfile = paste0("cbb.html"))
    doc <- htmlParse("cbb.html")
    g <- getNodeSet(doc, "//*[@id='players_per_game']/tfoot/tr/td[3]")
    mp <- getNodeSet(doc, "//*[@id='players_per_game']/tfoot/tr/td[5]")
    (cbb_df[i, ] <- c(all_urls[i], as.numeric(xmlValue(g[[1]])),
                     as.integer(as.numeric(xmlValue(mp[[1]])
                                           ) * 
                                  as.numeric(xmlValue(g[[1]])
                                             )
                                  )
                      )
      )
    free(doc)
  }
}
```

```{r, echo=TRUE}
# We have 1180 rows of data
nrow(cbb_df)
head(cbb_df)
```

```{r, echo=TRUE}
library(RSQLite)
dcon <- dbConnect(SQLite(), dbname = "stat405_final_project.db")
```

```{r, echo=TRUE}
# We have already merged cbb_df with main database, called AllRookieDataWithCBB, through DB Browser
dbListTables(dcon)

# We show first 1000 rows here
# Each row represents a game played by a rookie, so if a rookie played 80 games, his
# college stats will show up 80 times, but we decide to sacrifice redundancy for 
# future simplicity on manipulations
res <- dbSendQuery(conn = dcon, "
SELECT *
FROM AllRookieDataWithCBB
LIMIT 1000;
")
mydf <- dbFetch(res, -1)
dbClearResult(res)
View(mydf)
```

```{r, echo=TRUE}
dbDisconnect(dcon)
```

