---
title: "Killer Plot"
author: "Group 8"
date: "12/1/2019"
output: pdf_document
---

```{r, echo=TRUE, message=FALSE}
library(ggplot2)
library(plyr)
library(scales)
library(zoo)
library(plotly)
library(dplyr)
install.packages("webshot")
webshot::install_phantomjs()

library(webshot)
library(rmarkdown)

rmdshot("testPres.Rmd", "document.pdf")
```

```{r, echo=TRUE}
df <- read.csv("data/AllRookieData7.0.csv")
```

```{r, echo=TRUE}
# according to quantile
df$intl_group[df$intl_minutes >= 2 & df$intl_minutes < 682] = 1
df$intl_group[df$intl_minutes >= 682 & df$intl_minutes < 1249] = 2
df$intl_group[df$intl_minutes >= 1249 & df$intl_minutes < 3279] = 3
df$intl_group[df$intl_minutes >= 3279 & df$intl_minutes <= 13659] = 4
```

```{r, echo=TRUE}
df <- df %>% mutate(pre_nba_group = case_when(
        cbb_group == 1 & is.na(intl_group) ~ 1,
        cbb_group == 2 & is.na(intl_group) ~ 2, 
        cbb_group == 3 & is.na(intl_group) ~ 3,
        cbb_group == 4 & is.na(intl_group) ~ 4,
        is.na(cbb_group) & intl_group == 1 ~ 5,
        is.na(cbb_group) & intl_group == 2 ~ 6,
        is.na(cbb_group) & intl_group == 3 ~ 7,
        is.na(cbb_group) & intl_group == 4 ~ 8,
        is.na(cbb_group) & is.na(intl_group) ~ 9,
        !is.na(cbb_group) & !is.na(intl_group) ~ 10))
write.csv(df, "data/AllRookieDataWithDraftPos.csv")
```

```{r, echo=TRUE}
df %>% mutate(pre_nba_group = case_when(
        Month == 10 & MonthBin == 1 ~ 1,
        Month == 10 & MonthBin == 2 ~ 2, 
        Month == 10 & MonthBin == 3 ~ 3,
        cbb_group == 4 & is.na(intl_group) ~ 4,
        is.na(cbb_group) & intl_group == 1 ~ 5,
        is.na(cbb_group) & intl_group == 2 ~ 6,
        is.na(cbb_group) & intl_group == 3 ~ 7,
        is.na(cbb_group) & intl_group == 4 ~ 8,
        is.na(cbb_group) & is.na(cbb_group) ~ 9,
        !is.na(cbb_group) & !is.na(cbb_group) ~ 10)) 
```

```{r, echo=TRUE}
plot_df <- read.csv("data/GroupedMeanGSRS3.0.csv")
change_df <- read.csv("data/grouped_mean_gs2.0.csv")
```

```{r, echo=TRUE}
quantile(df$game_score, 0.05)
```
```{r, echo=TRUE}
df_rs <- df[df$MonthSegment < 21,]
df_gs36n <- df_rs[12.0 >= df_rs$game_score_per_36 & df_rs$game_score_per_36 >= 3.085714,]
plot_df <- summarise(group_by(df_gs36n, pre_nba_group, pre_nba_group_str, MonthStr, MonthSegment, MonthBin, round), 
                     mean_gs=mean(game_score), mean_gs_per_36 = mean(game_score_per_36), size = n())

plot_df <- plot_df %>%
  mutate(bin_date = case_when(MonthBin == 1 ~ "1st-10th",
                              MonthBin == 2 ~ "11th-20th",
                              MonthBin == 3 ~ "21st-end of month"),
         draft_round = case_when(round == 1 ~ "1st round",
                                 round == 2 ~ "2nd round",
                                 round == 3 ~ "Undrafted"))
plot_df <- plot_df %>%
  mutate(text = paste0("Time: ", MonthStr, "\t", bin_date, "\n", "Pre-NBA Group: ", pre_nba_group_str, "\n","Draft Pos: ", draft_round,"\n", "Size: ", size, "\n", "Avg. Game Score: ", round(mean_gs_per_36, 2)))
kp <- ggplot(plot_df, aes(MonthBin, round, fill = mean_gs_per_36, text=text)) + 
  geom_tile(colour = "white") +
  scale_fill_gradient(low="green", high="red") + 
  facet_grid(pre_nba_group~MonthStr) + scale_y_continuous(trans="reverse") + 
  labs(x="10-day Period of Month",
       y="Group of Rookies",
       title = "Game Score Per 36 Minutes Heatmap (25th %ile - 75th %ile)", 
       subtitle= "Performance change every 10 days", 
       fill="Game Score Per 36 Minutes")
ggplotly(kp, tooltip = "text")
```

```{r, echo=TRUE}
change_df <- change_df %>%
  mutate(month_str = case_when(m == 1 ~ "4 (Jan)",
                              m == 2 ~ "5 (Feb)",
                              m == 3 ~ "6 (Mar)",
                              m == 4 ~ "7 (Apr)",
                              m == 10 ~ "1 (Oct)",
                              m == 11 ~ "2 (Nov)",
                              m == 12 ~ "3 (Dec)")
         )
ggplot(change_df, aes(m, pre_nba_group, fill = pct_change)) + 
  geom_tile(colour = "white") +
  scale_fill_gradient(low="green", high="red") + 
  scale_y_continuous(trans="reverse") + 
  labs(x="10-day Period of Month",
       y="Group of Rookies",
       title = "Game Score Heatmap (5th %ile - 95th %ile)", 
       subtitle= "Performance change every 10 days", 
       fill="Game Score")
```
