---
title: "Missing Value Box Score"
author: "Group 8"
date: "11/26/2019"
output: pdf_document
---


```{r, echo=TRUE}
library(stringr)
library(dplyr)
library(XML)
library(RCurl)
library(stringr)
```

```{r, echo=TRUE}
data = read.csv("MissingValsRookieYrBoxScore.csv")
```

```{r, echo=TRUE}
# The format of player url is firstname-lastname-1, so we create a new column called
# br_url which consists of lowercase name and replace whitespace with "-"

# after paste it becomes "carmelo - anthony - 1", so in order to eliminate space we
# use str_replace_all to replace with ""

# then we added a new column called "br_url" for scraping usage
data$br_url <- str_replace_all(
  paste(
    str_to_lower(data$First_Name), "-", 
    str_to_lower(data$Last_Name), "-", "1"), 
  " ", "")
write.csv(data, "MissingValsRookieYrBoxScorewithURL.csv")
```

```{r, echo=TRUE}
# get urls from br_url column
all_urls <- as.vector(unique(data$br_url))
# get the length of urls
nurls <- length(all_urls)
# create a dataframe for players with NCAA experience
cbb_df <- data.frame(matrix(ncol = 3, nrow = nurls))
```

```{r, echo=TRUE}
# Scrape college careers
for (i in 1:nurls) {
  # get the appopriate url address
  u <- paste0("https://sports-reference.com/cbb/players/",
              all_urls[i],".html")
  if (url.exists(url = u)) {
    download.file(u, destfile = paste0("cbb.html"))
    doc <- htmlParse("cbb.html")
    g <- getNodeSet(doc, "//*[@id='players_per_game']/tfoot/tr/td[3]")
    mp <- getNodeSet(doc, "//*[@id='players_per_game']/tfoot/tr/td[5]")
    (cbb_df[i, ] <- c(all_urls[i], as.numeric(xmlValue(g[[1]])),
                     as.integer(as.numeric(xmlValue(mp[[1]])
                                           ) * 
                                  as.numeric(xmlValue(g[[1]])
                                             )
                                  )
                      )
      )
    free(doc)
  }
  
}
names(cbb_df)=c('nameurl','col_games','col_minutes')
```

```{r, echo=TRUE}
write.csv(cbb_df, "missing_ncaa.csv")
```

```{r, echo=TRUE}
f2 <- function(x) { u <- unique(x) ; data.frame(uniqueValue=u, firstIndex=match(u, x))}
# select first index of unique elements (matching the draft year)
index = f2(data$br_url)$firstIndex
urls <- unique(as.character(data$br_url))
nurls <- length(urls)
#url, year, games, minutes
intl_df = data.frame(
  Name=numeric(),
  Year=numeric(),
  Game=numeric(), 
  Minute=numeric()) 
compute_intl_df <- function(nurls) {
  
}

for (i in 1:nurls) {
  name = urls[i]
  cur_url <- paste0("https://www.basketball-reference.com/international/players/", urls[i],".html")
  count = 1
  if (url.exists(url = cur_url)) {
    # print(cur_url)
    download.file(cur_url, destfile = "international.html")
    doc <- htmlParse("international.html")
    draft_year = data[index[i], ]$season_id
    
    # //*[@id="totals-all-reg"]/tbody/tr[1]/th/a
    xpath_yr = paste0("//*[@id=\"totals-all-reg\"]/tbody/tr[", count,"]/th/a")
    yr <- getNodeSet(doc, xpath_yr)
    year = as.numeric(substr(as.character(xmlValue(yr[[1]])), 1, 4))
    
    xpath_g = paste0("//*[@id=\"totals-all-reg\"]/tbody/tr[", count, "]/td[4]")
    g = getNodeSet(doc, xpath_g)
    games = as.numeric(xmlValue(g[[1]]))
    
    xpath_mi = paste0("//*[@id=\"totals-all-reg\"]/tbody/tr[", count, "]/td[5]")
    mi <- getNodeSet(doc, xpath_mi)
    minutes = as.numeric(xmlValue(mi[[1]]))
    # print(minutes)
    # print(name)
    while (!is.na(year) & year < draft_year) {
      if (urls[i] == "milos-teodosic-1") {
        print(year)
      }
      intl_df[nrow(intl_df) + 1, ] = c(name, as.numeric(year), as.numeric(games), as.numeric(minutes))
      count = count + 1
      xpath_yr = paste0("//*[@id=\"totals-all-reg\"]/tbody/tr[", count,"]/th/a")
      yr <- getNodeSet(doc, xpath_yr)
      year = as.numeric(substr(as.character(xmlValue(yr[[1]])), 1, 4))
      
      xpath_g = paste0("//*[@id=\"totals-all-reg\"]/tbody/tr[", count, "]/td[4]")
      g = getNodeSet(doc, xpath_g)
      games = as.numeric(xmlValue(g[[1]]))
      
      xpath_mi = paste0("//*[@id=\"totals-all-reg\"]/tbody/tr[", count, "]/td[5]")
      mi <- getNodeSet(doc, xpath_mi)
      minutes = as.numeric(xmlValue(mi[[1]]))
    }
    free(doc)
  }
}

intl_df$Game = as.numeric(intl_df$Game)
intl_df$Minute = as.numeric(intl_df$Minute)
# sum up minutes and points
new_df = aggregate(cbind(Game_INTL=intl_df$Game, Minute_INTL=intl_df$Minute), by=list(Name=intl_df$Name), FUN=sum)

quantile(new_df$Minute)
new_df$group[new_df$Minute >= 2 & new_df$Minute < 530] = 1
new_df$group[new_df$Minute >= 530 & new_df$Minute < 1125] = 2
new_df$group[new_df$Minute >= 1125 & new_df$Minute < 3061] = 3
new_df$group[new_df$Minute >= 3061 & new_df$Minute <= 13659] = 4
write.csv(intl_df,"intl_game_min_per_season_before_NBA.csv", row.names = FALSE)
write.csv(new_df,"intl_game_min_before_NBA.csv", row.names = FALSE)

```

```{r, echo=TRUE}
rookie <- read.csv('AllRookieData.csv')
# str(rookie)
# head(rookie$Date_EST)
rookie$Month = as.numeric(substr(rookie$Date_EST, 1, 2))
rookie$MonthBin[as.numeric(substr(rookie$Date_EST, 4, 5)) <= 10] = 1
rookie$MonthBin[as.numeric(substr(rookie$Date_EST, 4, 5)) <= 20 & as.numeric(substr(rookie$Date_EST, 4, 5)) > 10] = 2
rookie$MonthBin[as.numeric(substr(rookie$Date_EST, 4, 5)) > 20] = 3
write.csv(rookie, 'AllRookieDataMonthBin.csv')
```